services:
  postgres:
    image: postgres:16
    container_name: postgres-16
    environment:
      POSTGRES_DB: petdb
      POSTGRES_USER: pet
      POSTGRES_PASSWORD: pet
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    container_name: redis-7
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-1234}
    ports: ["6379:6379"]
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-1234}", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build: ../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petdb
      SPRING_DATASOURCE_USERNAME: pet
      SPRING_DATASOURCE_PASSWORD: pet
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD:-1234}
    depends_on: [postgres, redis]
    ports: ["8080:8080"]

  frontend:
    build: ../frontend
    ports: ["4200:4200"]
    environment: [ "CHOKIDAR_USEPOLLING=true" ]
    volumes:
      - ../frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  redis-data:

networks:
  app-network:
    driver: bridge
